# Generated by Django 3.0.5 on 2020-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=15)),
                ('AdmissionDate', models.DateField(auto_now=True)),
                ('StudentName', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Phone', models.CharField(max_length=11)),
                ('Class', models.CharField(max_length=5)),
                ('Section', models.CharField(max_length=10)),
                ('Special', models.FloatField(default=0)),
                ('FeesType', models.CharField(max_length=10)),
                ('Ammount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
