# Generated by Django 3.0.5 on 2020-04-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice',
        ),
    ]
